sudo: required
language: c
script: sudo make install && sudo make uninstall && echo "deb [trusted=yes] http://hydro.nexus-software.fr/pamela ./" >> /etc/apt/sources.list && apt-get update && apt-get install -y pamela && apt-get remove -y pamela
