sudo: required
language: c
script: sudo make install && sudo make uninstall && sudo su -c "echo 'deb [trusted=yes] http://hydro.nexus-software.fr/pamela ./' >> /etc/apt/sources.list" && sudo apt-get update && sudo apt-get install -y pamela && sudo apt-get remove -y pamela
